version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs_app

hooks:
  BeforeInstall:
    # Clean the target directory to avoid file conflicts and install dependencies
    - script: |
        rm -rf /home/ec2-user/nodejs_app/*
        # Install dependencies after cleanup
        cd /home/ec2-user/nodejs_app
        npm install

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
